/*
 * MyTable.java
 *
 * Created on 23 de julio de 2009, 17:14
 */

package com.openbravo.sync.panel;

import com.openbravo.pos.forms.AppLocal;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JViewport;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author  Mikel Irurita
 */
public class MyTable extends JPanel {

    private MyJTable table;
    private MyDefaultTableModel model;
    TableRowSorter<TableModel> sorter;

    /** Creates new form MyTable */
    public MyTable() {
        initComponents();
        init();
    }

    private void init() {
       table = new MyJTable();
       table.setAutoCreateRowSorter(true);
       table.setFillsViewportHeight(true);
       jTextFilter.getDocument().addDocumentListener(new FilterListener());

    }

    public void createTable(int row, int col) {
        model = new MyDefaultTableModel(row, col);
        table.setModel(model);
        sorter  = new TableRowSorter<TableModel>(model);
        table.setRowSorter(sorter);
    }

    public void createTable(Object[][] data, Object[] header) {
        model = new MyDefaultTableModel(data, header);
        table.setModel(model);
        sorter  = new TableRowSorter<TableModel>(model);
        table.setRowSorter(sorter);
    }

    public void addLine(Object[] row){
        model.addRow(row);
    }

    public void refresh() {
        jScrollPane1.setViewportView(table);
        //jScrollPane1.revalidate();
        //repaint();
    }

    public void clear() {
        createTable(0, 0);
        jTextFilter.setText("");
        refresh();
    }

    public MyDefaultTableModel getTableModel() {
        return model;
    }

    private void newFilter() {
        RowFilter<TableModel, Object> rf = null;

        try {
            rf = RowFilter.regexFilter(jTextFilter.getText(), 1);
        } catch (java.util.regex.PatternSyntaxException e) {
            return;
        }
        sorter.setRowFilter(rf);
    }

    public class FilterListener implements DocumentListener {

        @Override
        public void insertUpdate(DocumentEvent arg0) {
             newFilter();
        }

        @Override
        public void removeUpdate(DocumentEvent arg0) {
             newFilter();
        }

        @Override
        public void changedUpdate(DocumentEvent arg0) {
             newFilter();
        }

    }

    public class MyDefaultTableModel extends DefaultTableModel {

        public MyDefaultTableModel(int row, int col) {
            super(row, col);
        }

        public MyDefaultTableModel(Object[][] content, Object[] header) {
            super(content, header);
        }


        @Override
        public boolean isCellEditable(int row, int col) {
            return false;
        }
    }

    public class MyJTable extends JTable {

        public MyJTable() {
            super();
        }

        @Override
        public boolean getScrollableTracksViewportWidth() {
   	if (autoResizeMode != AUTO_RESIZE_OFF) {
 	    if (getParent() instanceof JViewport) {
 		return (((JViewport)getParent()).getWidth() > getPreferredSize().width);
 	    }
 	}
 	return false;
    }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        jTextFilter = new javax.swing.JTextField();

        jLabel1.setText(AppLocal.getIntString("label.filter")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFilter, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFilter;
    // End of variables declaration//GEN-END:variables

}
