-- NORD POS is a fork of Openbravo POS.
-- Copyright (C) 2009-2016 Nord Trading Ltd. 
-- <http://sourceforge.net/p/nordpos/>
-- This file is part of NORD POS.
-- NORD POS is free software: you can redistribute it and/or modify it under the
-- terms of the GNU General Public License as published by the Free Software
-- Foundation, either version 3 of the License, or (at your option) any later
-- version.
-- NORD POS is distributed in the hope that it will be useful, but WITHOUT ANY
-- WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
-- A PARTICULAR PURPOSE. See the GNU General Public License for more details.
-- You should have received a copy of the GNU General Public License along with
-- NORD POS. If not, see <http://www.gnu.org/licenses/>.

-- Database upgrade script for MYSQL
-- NORD POS v3.0.6CE -> NORD POS v3.1.0CE  

-- final script

CREATE TABLE GEOLAYERS (
    ID VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    VISIBLE BIT DEFAULT b'1' NOT NULL,    
    ICON MEDIUMBLOB,
    COLOUR VARCHAR(50),
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE UNIQUE INDEX GEOLAYERS_NAME_INX ON GEOLAYERS(NAME);
INSERT INTO GEOLAYERS(ID, NAME) VALUES ('0', 'Cities');

CREATE TABLE GEOMARKERS (
    ID VARCHAR(255) NOT NULL,
    NAME VARCHAR(255),
    LATITUDE DOUBLE NOT NULL,
    LONGITUDE DOUBLE NOT NULL,
    VISIBLE BIT DEFAULT b'1' NOT NULL,
    GEOLAYER VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT GEOMARKERS_FK_1 FOREIGN KEY (GEOLAYER) REFERENCES GEOLAYERS(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO GEOMARKERS(ID, NAME, LATITUDE, LONGITUDE, GEOLAYER) VALUES ('1', 'Astana', '51.14', '71.44', '0');
INSERT INTO GEOMARKERS(ID, NAME, LATITUDE, LONGITUDE, GEOLAYER) VALUES ('2', 'Madrid', 40.39, -3.72, '0');
INSERT INTO GEOMARKERS(ID, NAME, LATITUDE, LONGITUDE, GEOLAYER) VALUES ('3', 'Istanbul', 41.01, 28.97, '0');
INSERT INTO GEOMARKERS(ID, NAME, LATITUDE, LONGITUDE, GEOLAYER) VALUES ('4', 'London', 51.49, 0.0, '0');
INSERT INTO GEOMARKERS(ID, NAME, LATITUDE, LONGITUDE, GEOLAYER) VALUES ('5', 'Paris', 48.86, 2.36, '0');
INSERT INTO GEOMARKERS(ID, NAME, LATITUDE, LONGITUDE, GEOLAYER) VALUES ('6', 'Moscow', 55.75, 37.62, '0');
INSERT INTO GEOMARKERS(ID, NAME, LATITUDE, LONGITUDE, GEOLAYER) VALUES ('7', 'Beijing', 39.9, 116.39, '0');
INSERT INTO GEOMARKERS(ID, NAME, LATITUDE, LONGITUDE, GEOLAYER) VALUES ('8', 'Cairo',30.05, 31.24, '0');
INSERT INTO GEOMARKERS(ID, NAME, LATITUDE, LONGITUDE, GEOLAYER) VALUES ('9', 'Berlin', 52.51, 13.4, '0');
INSERT INTO GEOMARKERS(ID, NAME, LATITUDE, LONGITUDE, GEOLAYER) VALUES ('10', 'Rome', 41.90, 12.49, '0');
INSERT INTO GEOMARKERS(ID, NAME, LATITUDE, LONGITUDE, GEOLAYER) VALUES ('11', 'Delhi', 28.63, 77.22, '0');
INSERT INTO GEOMARKERS(ID, NAME, LATITUDE, LONGITUDE, GEOLAYER) VALUES ('12', 'Melbourne', -37.82, 145.0, '0');
INSERT INTO GEOMARKERS(ID, NAME, LATITUDE, LONGITUDE, GEOLAYER) VALUES ('13', 'Buenos Aires', -34.67, -58.46, '0');
INSERT INTO GEOMARKERS(ID, NAME, LATITUDE, LONGITUDE, GEOLAYER) VALUES ('14', 'Mexico City', 19.43, -99.14, '0');
INSERT INTO GEOMARKERS(ID, NAME, LATITUDE, LONGITUDE, GEOLAYER) VALUES ('15', 'New York', 40.78, -73.97, '0');

UPDATE ROLES SET PERMISSIONS = $FILE{/com/openbravo/pos/templates/Role.Administrator.xml} WHERE ID = '0';
UPDATE ROLES SET PERMISSIONS = $FILE{/com/openbravo/pos/templates/Role.Manager.xml} WHERE ID = '1';

UPDATE RESOURCES SET CONTENT = $FILE{/com/openbravo/pos/templates/Menu.Root.bsh} WHERE NAME = 'Menu.Root';

DELETE FROM SHAREDTICKETS;

UPDATE APPLICATIONS SET ID = $APP_ID{}, NAME = $APP_NAME{}, VERSION = $APP_VERSION{} WHERE ID = 'nordpos';