//    Openbravo POS is a point of sales application designed for touch screens.
//    Copyright (C) 2007-2009 Openbravo, S.L.
//    http://www.openbravo.com/product/pos
//
//    This file is part of Openbravo POS.
//
//    Openbravo POS is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    Openbravo POS is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with Openbravo POS.  If not, see <http://www.gnu.org/licenses/>.

package com.openbravo.pos.forms;

import javax.swing.JComponent;
import javax.swing.JPanel;
import com.openbravo.basic.BasicException;

/**
 *
 * @author adrianromero
 */
public class JPanelNull extends JPanel implements JPanelView {

    /** Creates new form JPanelNull */
    public JPanelNull(AppView oApp, Object o) {
       
        initComponents ();
        if (o instanceof Exception) {
            ((Exception) o).printStackTrace();
        }
        jtxtException.setText(o.toString());
    }

    public JComponent getComponent() {
        return this;
    }
    public String getTitle() {
        return null;
    }
    public void activate() throws BasicException {
    }
    public boolean deactivate() {
        return true;
    }    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        m_jLabelError = new javax.swing.JLabel();
        jscrException = new javax.swing.JScrollPane();
        jtxtException = new javax.swing.JTextArea();

        setLayout(null);

        m_jLabelError.setText(AppLocal.getIntString("Label.LoadError"));
        add(m_jLabelError);
        m_jLabelError.setBounds(30, 30, 490, 20);

        jtxtException.setEditable(false);
        jtxtException.setLineWrap(true);
        jtxtException.setWrapStyleWord(true);
        jscrException.setViewportView(jtxtException);

        add(jscrException);
        jscrException.setBounds(30, 70, 550, 180);

    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jscrException;
    private javax.swing.JTextArea jtxtException;
    private javax.swing.JLabel m_jLabelError;
    // End of variables declaration//GEN-END:variables

}
